---
kind: pipeline
name: develop

platform:
  os: linux
  arch: amd64

trigger:
  event:
    exclude:
      - pull_request
      - tag

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/base
    cache_from: hotio/base:develop
    tags:
      - develop

---
kind: pipeline
name: release-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/base
    cache_from: hotio/base
    tags:
      - ${DRONE_TAG}-linux-amd64

---
kind: pipeline
name: release-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/base
    cache_from: hotio/base
    build_args:
      - ARCH_S6=aarch64
      - ARCH_RCLONE=arm64
    tags:
      - ${DRONE_TAG}-linux-arm64

---
kind: pipeline
name: manifest

trigger:
  event:
    - tag

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: hotio/base:latest
    template: hotio/base:${DRONE_TAG}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - release-amd64
  - release-arm64
