---
kind: pipeline
name: dockerhub-sync

trigger:
  event:
    - push

steps:
- name: sync
  image: peterevans/dockerhub-description:2.1.0
  pull: always
  environment:
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    DOCKERHUB_PASSWORD:
      from_secret: docker_pass
    DOCKERHUB_REPOSITORY: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    README_FILEPATH: ./README.md
